### ISSUE TITLE
FATAL EXCEPTION  java.lang.NullPointerException: TokenResponse.getIdToken()' on a null object reference

### ISSUE THREAD

**Issue by Kolyall** [omkarmoghe/Pokemap#171]
After log in with Google acc

```
FATAL EXCEPTION: main
                                                                        Process: com.omkarmoghe.pokemap, PID: 28894
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.omkarmoghe.pokemap.controllers.net.GoogleService$TokenResponse.getIdToken()' on a null object reference
                                                                            at com.omkarmoghe.pokemap.controllers.net.GoogleManager$2.onResponse(GoogleManager.java:85)
                                                                            at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:158)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by s7092910** [comment]
Do you have a copy of the last network response from Logcat? Both headers and response body.

**Comment by comann** [comment]
@kyr0  Thanks for the update. FIxed on Dev tip.
