### ISSUE TITLE
[Bug] "POGOProtos.Map.Fort.FortDataOuterClass$FortData$Builder" missing method "getId".

### ISSUE THREAD

**Issue by Kolyall** [omkarmoghe/Pokemap#181]
Server is available, i'm online. 
- Long click to set location ->
  Searching runs

[Video](https://www.dropbox.com/s/dnc5c4vg6qk9dum/mobizen_20160726_151823.mp4?dl=1)

It happens if : 
- change location many times. 

OR :
- minimize the app
- stop service
- open the app again

```

07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err: java.lang.RuntimeException: Generated message class "POGOProtos.Map.Fort.FortDataOuterClass$FortData$Builder" missing method "getId".
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at com.google.protobuf.GeneratedMessage.getMethodOrDie(GeneratedMessage.java:1806)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at com.google.protobuf.GeneratedMessage.access$1100(GeneratedMessage.java:61)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at com.google.protobuf.GeneratedMessage$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessage.java:2095)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at com.google.protobuf.GeneratedMessage$FieldAccessorTable$SingularStringFieldAccessor.<init>(GeneratedMessage.java:2694)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at com.google.protobuf.GeneratedMessage$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessage.java:1944)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at POGOProtos.Map.Fort.FortDataOuterClass$FortData.internalGetFieldAccessorTable(FortDataOuterClass.java:327)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at com.google.protobuf.GeneratedMessage.getDescriptorForType(GeneratedMessage.java:108)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at com.google.protobuf.AbstractMessage.equals(AbstractMessage.java:119)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at java.util.ArrayList.remove(ArrayList.java:418)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at com.pokegoapi.api.map.MapObjects.update(MapObjects.java:190)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at com.pokegoapi.api.map.Map.getMapObjects(Map.java:312)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at com.pokegoapi.api.map.Map.getMapObjects(Map.java:250)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at com.pokegoapi.api.map.Map.getMapObjects(Map.java:185)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at com.pokegoapi.api.map.Map.getMapObjects(Map.java:175)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at com.omkarmoghe.pokemap.controllers.net.NianticManager$8.run(NianticManager.java:294)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at android.os.Looper.loop(Looper.java:158)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err: Caused by: java.lang.NoSuchMethodException: getId []
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at java.lang.Class.getMethod(Class.java:630)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at java.lang.Class.getMethod(Class.java:609)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:     at com.google.protobuf.GeneratedMessage.getMethodOrDie(GeneratedMessage.java:1804)
07-26 14:57:25.121 4220-4234/com.omkarmoghe.pokemap W/System.err:   ... 18 more
```

**Comment by comann** [comment]
Latest of Dev is Fixed.
