### ISSUE TITLE
Null pointer on Response

### ISSUE THREAD

**Issue by srshkmr** [omkarmoghe/Pokemap#22]
`FATAL EXCEPTION: OkHttp Dispatcher
                                                                      Process: com.omkarmoghe.pokemap, PID: 7925
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
                                                                          at com.omkarmoghe.pokemap.MainActivity$2$1.onResponse(MainActivity.java:153)
                                                                          at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
                                                                          at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                          at java.lang.Thread.run(Thread.java:818)`

**Comment by omkarmoghe** [comment]
need to do a null check there if server response was bad

**Comment by bsiver** [comment]
This appears to be fixed with af3e4659dceb90240de3eb9dca9652d1dc0b01e2

**Comment by bsiver** [comment]
This shouldn't occur after af3e4659dceb90240de3eb9dca9652d1dc0b01e2, which ensures the response is a 302 and has a `location` header
