### ISSUE TITLE
[Bug] com.pokegoapi.exceptions.LoginFailedException after log in with Google

### ISSUE THREAD

**Issue by Kolyall** [omkarmoghe/Pokemap#238]
- Login with Google
- Minimize the app
- Wait 10 min
- Open the app again
- Try to make search
- Nothing happens
- Go to App settings in device and terminate the app
- Open app again

[result]
- Login screen opens

Log:

```
07-27 13:41:24.527 7729-7816/com.omkarmoghe.pokemap W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
07-27 13:41:25.507 7729-7816/com.omkarmoghe.pokemap W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
07-27 13:41:25.947 7729-7816/com.omkarmoghe.pokemap D/libEGL: eglTerminate EGLDisplay = 0x95a6b38c
07-27 13:41:25.947 7729-7816/com.omkarmoghe.pokemap D/libEGL: eglTerminate EGLDisplay = 0x95a6b38c
07-27 13:41:25.967 7729-7729/com.omkarmoghe.pokemap V/ActivityThread: updateVisibility : ActivityRecord{22f99df token=android.os.BinderProxy@8dd942e {com.omkarmoghe.pokemap/com.omkarmoghe.pokemap.views.MainActivity}} show : false
07-27 13:41:25.997 7729-7822/com.omkarmoghe.pokemap E/libGLESv1: HWUI Protection: wrong call from hwui context F:ES1-glDeleteTexturesSEC
07-27 13:41:25.997 7729-7729/com.omkarmoghe.pokemap D/libEGL: eglTerminate EGLDisplay = 0xbec4872c
07-27 13:41:31.137 7729-7735/com.omkarmoghe.pokemap W/art: Suspending all threads took: 8.701ms
07-27 13:41:35.267 14233-14233/com.omkarmoghe.pokemap W/ResourcesManager: getTopLevelResources: /data/app/com.omkarmoghe.pokemap-2/base.apk / 1.0 running in com.omkarmoghe.pokemap rsrc of package null
07-27 13:41:35.287 14233-14233/com.omkarmoghe.pokemap W/System: ClassLoader referenced unknown path: /data/app/com.omkarmoghe.pokemap-2/lib/arm
07-27 13:41:35.387 14233-14233/com.omkarmoghe.pokemap W/ResourcesManager: getTopLevelResources: /data/app/com.omkarmoghe.pokemap-2/base.apk / 1.0 running in com.omkarmoghe.pokemap rsrc of package null
07-27 13:41:35.397 14233-14233/com.omkarmoghe.pokemap W/ResourcesManager: getTopLevelResources: /data/app/com.omkarmoghe.pokemap-2/base.apk / 1.0 running in com.omkarmoghe.pokemap rsrc of package null
07-27 13:41:35.507 14233-14233/com.omkarmoghe.pokemap W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
07-27 13:41:35.907 14233-14233/com.omkarmoghe.pokemap I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
07-27 13:41:35.917 14233-14233/com.omkarmoghe.pokemap I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
07-27 13:41:35.927 14233-14233/com.omkarmoghe.pokemap W/ResourcesManager: getTopLevelResources: /data/app/com.google.android.gms-1/base.apk / 1.0 running in com.omkarmoghe.pokemap rsrc of package null
07-27 13:41:36.127 14233-14233/com.omkarmoghe.pokemap D/ChimeraCfgMgr: Reading stored module config
07-27 13:41:36.137 14233-14245/com.omkarmoghe.pokemap I/art: Background sticky concurrent mark sweep GC freed 23156(1419KB) AllocSpace objects, 3(80KB) LOS objects, 25% free, 17MB/23MB, paused 12.707ms total 58.505ms
07-27 13:41:36.187 14233-14233/com.omkarmoghe.pokemap W/System: ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/0000000a/n/armeabi-v7a
07-27 13:41:36.187 14233-14233/com.omkarmoghe.pokemap W/System: ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/0000000a/n/armeabi
07-27 13:41:36.207 14233-14233/com.omkarmoghe.pokemap D/ChimeraFileApk: Primary ABI of requesting process is armeabi-v7a
07-27 13:41:36.217 14233-14233/com.omkarmoghe.pokemap D/ChimeraFileApk: Classloading successful. Optimized code found.
07-27 13:41:36.267 14233-14233/com.omkarmoghe.pokemap D/PokemapSharedPreference: getLoginInfo: info = [eyJhbGciOiJSUzI1NiIsImtpZCI6IjUwNzgyYmNmMGE5NzQxZTZiZjkwMjY2ZGMzNTY4YWE5MDc5MWYxNmYifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhdF9oYXNoIjoiMVZFMnlFQjNyeENXdE9EWkZKNkhBQSIsImF1ZCI6Ijg0ODIzMjUxMTI0MC03M3JpM3Q3cGx2azk2cGo0Zjg1dWo4b3RkYXQyYWxlbS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjEwOTQ1OTI4NzQ0NjQ3OTMzMzEwMiIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhenAiOiI4NDgyMzI1MTEyNDAtNzNyaTN0N3Bsdms5NnBqNGY4NXVqOG90ZGF0MmFsZW0uYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJoZCI6Im1vYmV4cy5jb20iLCJlbWFpbCI6Im5pa29sYXkudW51Y2hla0Btb2JleHMuY29tIiwiaWF0IjoxNDY5NjExODk5LCJleHAiOjE0Njk2MTU0OTl9.nSsO2aY4T4z0T7g_1fX2iHHtGUAXWw7Oii_LKyRE3onjMtDzENll9jo3AzKtGk5gl_7zyI0TPCwJL7RYoCLYHB07bpz4Xn7m5QZzNx7aQrIJmpTJVGPf_Z4w0YEjM1XxSOetogfHjKromSdp9R5OAxhBHFSkKV5gr_pQAMv1w9sea_G-SlD-i4K35bu-kIj5u8h3ivzN7ZAEP6yP58Lu2DuTO6SlyjdYZFA5NKV9KOsgccGbOWotDuGE_uNekzu_tY11VhRx_UhugkIt_pkwZTw9-2GL3GHytsyt0Y-tYpRT9QbKEWbvzu8OSzpXbKpbks4spwHnmwlkFUGjUrnTmw, 1/2Jj8Dnr0MciIfWvIxLUpID_eh35AMsw8Qua0cR5H-GU]
07-27 13:41:36.267 14233-14233/com.omkarmoghe.pokemap D/NianticManager: setLoginInfo: LoginInfo = com.omkarmoghe.pokemap.models.login.GoogleLoginInfo@c3eb1a6
07-27 13:41:36.327 14233-14239/com.omkarmoghe.pokemap W/art: Suspending all threads took: 54.070ms
07-27 13:41:36.337 14233-14262/com.omkarmoghe.pokemap I/System.out: D/RequestHandler: Authenticated with static token
07-27 13:41:36.357 14233-14233/com.omkarmoghe.pokemap D/SecWifiDisplayUtil: Metadata value : none
07-27 13:41:36.377 14233-14233/com.omkarmoghe.pokemap D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{77ccf94 I.E...... R.....ID 0,0-0,0}
07-27 13:41:36.377 14233-14278/com.omkarmoghe.pokemap D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
07-27 13:41:36.417 14233-14262/com.omkarmoghe.pokemap I/System.out: D/RequestHandler: Authenticated with static token
07-27 13:41:36.427 14233-14278/com.omkarmoghe.pokemap I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build:  (Ia10634f51b)
                                                                    OpenGL ES Shader Compiler Version: E031.29.00.00
                                                                    Build Date: 01/28/16 Thu
                                                                    Local Branch: ss
                                                                    Remote Branch: 
                                                                    Local Patches: 
                                                                    Reconstruct Branch: 
07-27 13:41:36.437 14233-14278/com.omkarmoghe.pokemap D/libEGL: eglInitialize EGLDisplay = 0xae2847c4
07-27 13:41:36.437 14233-14278/com.omkarmoghe.pokemap I/OpenGLRenderer: Initialized EGL, version 1.4
07-27 13:41:36.537 14233-14233/com.omkarmoghe.pokemap W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
07-27 13:41:36.567 14233-14233/com.omkarmoghe.pokemap D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
07-27 13:41:37.277 14233-14262/com.omkarmoghe.pokemap W/System.err: com.pokegoapi.exceptions.LoginFailedException
07-27 13:41:37.277 14233-14262/com.omkarmoghe.pokemap W/System.err:     at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:133)
07-27 13:41:37.277 14233-14262/com.omkarmoghe.pokemap W/System.err:     at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:79)
07-27 13:41:37.277 14233-14262/com.omkarmoghe.pokemap W/System.err:     at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
07-27 13:41:37.277 14233-14262/com.omkarmoghe.pokemap W/System.err:     at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
07-27 13:41:37.277 14233-14262/com.omkarmoghe.pokemap W/System.err:     at com.omkarmoghe.pokemap.controllers.net.NianticManager$6.run(NianticManager.java:280)
07-27 13:41:37.277 14233-14262/com.omkarmoghe.pokemap W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
07-27 13:41:37.277 14233-14262/com.omkarmoghe.pokemap W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-27 13:41:37.277 14233-14262/com.omkarmoghe.pokemap W/System.err:     at android.os.Looper.loop(Looper.java:158)
07-27 13:41:37.277 14233-14262/com.omkarmoghe.pokemap W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
07-27 13:41:37.277 14233-14262/com.omkarmoghe.pokemap E/NianticManager: Failed to PTC login using PoGoAPI via login(). Raised: null
07-27 13:41:37.297 14233-14233/com.omkarmoghe.pokemap D/LoginActivity: authFailed() called with: message = [null]
07-27 13:41:37.347 14233-14233/com.omkarmoghe.pokemap W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
07-27 13:41:37.347 14233-14233/com.omkarmoghe.pokemap W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
07-27 13:41:37.357 14233-14233/com.omkarmoghe.pokemap I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@d3667e7 time:136411011

```

**Comment by s7092910** [comment]
At any point did you login with the PTC recently?

**Comment by Kolyall** [comment]
@s7092910 i don't remember
