### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by tdjsnelling** [omkarmoghe/Pokemap#300]
Have just pulled latest changes and app crashes on launch. 

`07-28 11:43:28.677 30063-30063/com.omkarmoghe.pokemap E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.omkarmoghe.pokemap, PID: 30063
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.omkarmoghe.pokemap/com.omkarmoghe.pokemap.views.LoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                            at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
                                                                            at com.omkarmoghe.pokemap.controllers.app_preferences.PokemapSharedPreferences.getLoginInfo(PokemapSharedPreferences.java:66)
                                                                            at com.omkarmoghe.pokemap.views.LoginActivity.onCreate(LoginActivity.java:153)
                                                                            at android.app.Activity.performCreate(Activity.java:6245)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                            at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
`

**Comment by Giggitybyte** [comment]
Does the latest [dev build](https://github.com/omkarmoghe/Pokemap/releases) work for you? Building the app through Android Studio never seems to work well for me.

**Comment by tdjsnelling** [comment]
Have not tried the build yet, this is the first problem I've had with android studio though. Been fine thus far.

**Comment by xomikronx** [comment]
Just pulled latest changes 10 minutes ago.  It's crashing on me too.

**Comment by s7092910** [comment]
Fix in PR #313
