### ISSUE TITLE
FATAL EXCEPTION when adding : compile 'com.google.android.gms:play-services-analytics:9.2.1'

### ISSUE THREAD

**Issue by JawharKod** [omkarmoghe/Pokemap#340]
Hi ! When i try to add  play-services-analytics the app crash, this i what i get : 

`07-29 16:12:48.886 9045-9045/com.omkarmoghe.pokemap E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      java.lang.ExceptionInInitializerError
                                                                          at com.omkarmoghe.pokemap.views.LoginActivity.onCreate(LoginActivity.java:63)
                                                                          at android.app.Activity.performCreate(Activity.java:5104)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
                                                                          at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                          at android.os.Looper.loop(Looper.java:137)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:511)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: java.lang.NoClassDefFoundError: retrofit2.Retrofit$Builder
                                                                          at com.omkarmoghe.pokemap.controllers.net.NianticManager.<init>(NianticManager.java:132)
                                                                          at com.omkarmoghe.pokemap.controllers.net.NianticManager.<clinit>(NianticManager.java:73)
                                                                          at com.omkarmoghe.pokemap.views.LoginActivity.onCreate(LoginActivity.java:63) 
                                                                          at android.app.Activity.performCreate(Activity.java:5104) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                                          at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                          at android.os.Looper.loop(Looper.java:137) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 

  `
This is what i've add ...

 //Google Play Services
    compile 'com.google.android.gms:play-services-maps:9.2.1'
    compile 'com.google.android.gms:play-services-location:9.2.1'
    compile 'com.google.android.gms:play-services-analytics :9.2.1' 

Any idea why this happen ?

EDIT NOTE : The problem is caused by : com.google.android.gms:play-services-ads:9.2.1 and other google play services

**Comment by CarstenHouweling** [comment]
Version missmatch perhaps?

**Comment by JawharKod** [comment]
@CarstenHouweling any idea how i can fix that ? 
I was strugling with this error since 3 days. Now i delete all the change i've made, and this line is the only thing i've added :  compile 'com.google.android.gms:play-services-analytics :9.2.1'

I tried using all the services too compile 'com.google.android.gms:play-services :9.2.1' and still have the same error :(

any help or idea would be more than welcome !

**Comment by CarstenHouweling** [comment]
adding compile 'com.google.android.gms:play-services-analytics:9.2.1' works fine for me

**Note** you have a space between analytics and :9.2.1 - don't know if intentional or whatever...

**Comment by CarstenHouweling** [comment]
@jkodad Could you add the new Firebase stuff instead of the old play analytics please?

**Comment by omkarmoghe** [comment]
> `Caused by: java.lang.NoClassDefFoundError: retrofit2.Retrofit$Builder`

Do you have all the correct retrofit dependencies?

**Comment by JawharKod** [comment]
@omkarmoghe yes ! (at least i supose that ... since the app was working like a charm before i tried to add more google services)
@CarstenHouweling I can't, as it's a school project and we have to work with google services.

I cleaned my project, ans restarted android studio, i removed analytics and tried instead : the conflict was with this service : "ads" , can you please test it on your machine, maybe i have something wrong on my android studio paramaters

 compile 'com.google.android.gms:play-services-ads:9.2.1'

if it's working for you please let me know

**Comment by omkarmoghe** [comment]
did you install them with your SDK manager?

**Comment by JawharKod** [comment]
@omkarmoghe I'm really glad that you are helping me ! 
No i didn't, i searched on the sdk manager, couldn't find it, i searched on google to on how to install it, i'm a bit lost...

**Comment by s7092910** [comment]
Try doing a clean build.

**Comment by rohanjain1** [comment]
so, lemme get this straight, you're cloning our repo, trying to add AdMob to it [for whatever purpose] and asking for help doing so?
Also the issue is probably a mismatch. re-check versions in gradle
